// this is the storage account for the reports files
// It is used to store the reports files generated by the function app
resource "azurerm_storage_account" "saccount1" {
    name                     = "sa${ var.project }${ var.environment }"
    resource_group_name      = azurerm_resource_group.rg.name
    location                 = var.location
    account_tier             = "Standard"
    account_replication_type = "LRS"

    tags = var.tags
}

// This is the storage account for the function app
// It is used to store the function app code and other related files
resource "azurerm_storage_account" "saccount2" {
    name                     = "sa${ var.project }func${ var.environment }"
    resource_group_name      = azurerm_resource_group.rg.name
    location                 = var.location
    account_tier             = "Standard"
    account_replication_type = "LRS"

    tags = var.tags
}

// This is the storage container for the reports files
resource "azurerm_storage_container" "c1" {
    name = "reports"
    container_access_type = "private"
    storage_account_id = azurerm_storage_account.saccount1.id
}
// This is the storage queue for the reports requests 
resource "azurerm_storage_queue" "q1" {
    name = "requests"
    storage_account_name = azurerm_storage_account.saccount1.name
}